source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BLMultiColorLoader_Example', :exclusive => true do
  pod 'BLMultiColorLoader', :path => '../'
end

target 'BLMultiColorLoader_Tests', :exclusive => true do
  pod 'BLMultiColorLoader', :path => '../'

  
end
